min_records_in_table: 58000000
max_records_in_table: 58000000000
parallel_readers: 2
parallel_writers: 2

databases:
  postgres:
    adapter: postgresql
    url: 'postgres://postgres:postgres@postgres:5432/postgres'
    pool: 10

test_cases:
  # - ten_thousand_inserts
  - parallel_simple_reads_and_writes_with_min_records
  # - parallel_simple_reads_and_writes_with_max_records
  # - parallel_complex_reads_and_writes_with_min_records
  # - parallel_complex_reads_and_writes_with_max_records
