min_records_in_table: 58000000
max_records_in_table: 58000000000
parallel_readers: 2
parallel_writers: 2

databases:
  postgres:
    adapter: postgresql
    url: 'postgres://postgres:postgres@127.0.0.1:5432/postgres'
    pool: 20
  timescale_db:
    adapter: postgresql
    url: 'postgres://postgres:postgres@127.0.0.1:5432/bmx_test'
    pool: 20

test_cases:
  # - ten_thousand_random_inserts
  # - ten_thousand_sequential_ascending_inserts
  # - ten_thousand_sequential_descending_inserts
  # - parallel_simple_reads_and_random_writes_with_min_records
  # - parallel_simple_reads_and_random_writes_with_max_records
  # - parallel_complex_reads_and_random_writes_with_min_records
  # - parallel_complex_reads_and_random_writes_with_max_records
  - parallel_complex_reads_and_sequential_writes_with_min_records
