user_count: 10_000
device_count: 10_000
event_count: 58_000_000

parallel_readers: 2
parallel_writers: 2

databases:
  maria_db:
    adapter: mysql2
    url: 'mysql2://root:password1234@mariadb/test'
    pool: 20
  postgres:
    adapter: postgresql
    url: 'postgres://postgres:postgres@postgres:5432/postgres'
    pool: 20
  timescale_db:
    adapter: postgresql
    url: 'postgres://postgres:postgres@timescaledb:5432/postgres'
    pool: 20

test_cases:
  - ten_thousand_random_inserts
  - ten_thousand_sequential_ascending_inserts
  - ten_thousand_sequential_descending_inserts
  - parallel_simple_reads_and_random_writes
  # - parallel_simple_reads_and_sequential_writes
  - parallel_complex_reads_and_random_writes
  # - parallel_complex_reads_and_sequential_writes
